# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"kitty" = ""
"zsh" = ""
"github" = ""
"amazon" = ""
"reddit" = ""
"youtube" = ""
"twitch" = ""
"twitter" = ""
"gitlab" = ""
"clojure" = ""
"hacker news" = ""
"discord" = "ﭮ"
"wikipedia" = ""
"whatsapp" = ""
"rust" = ""
"private browsing" = ""
"firefox" = ""
"file manager" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"nvim" = ""
"gthumb" = ""
"image" = ""
"menu" = ""
"calculator" = ""
"fragments" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
"disk usage" = ""
".pdf" = ""
