icons = "material-nf"

[theme]
name = "solarized-dark"

[theme.overrides]
separator = ""

[[block]]
block = "focused_window"
show_marks = "visible"
max_width = 70

[[block]]
block = "music"
buttons = ["play", "next"]
format = "{title}"

[[block]]
block = "memory"
display_type = "memory"
icons = false
format_mem = "{mem_used}"

[[block]]
block = "temperature"
collapsed = false
chip = "coretemp-isa-0000"
format = "{average}"
interval = 5

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "maildir"
interval = 40
inboxes = ["/home/p00f/Mail/BITS/INBOX", "/home/p00f/Mail/GMail/INBOX"]

[[block]]
block = "networkmanager"
device_format = "{icon}{name} {ap}"
on_click = "networkmanager_dmenu"

[[block]]
block = "time"
icons_format = " "
interval = 60
format = "%a %d/%m %R"
on_click = "wldash"
