format = """
┌ $username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$package\
$python\
$nix_shell\
$cmd_duration\
$status\
$line_break\
$jobs\
$shell\
└$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = "↑${count}"
diverged = "⇕:⇡${ahead_count}⇣${behind_count}"
behind = "↓${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
style = "green"

[status]
format = "[$symbol $status]($style) "
symbol = "✘"
style = "purple"
disabled = false

[git_branch]
format = "[$symbol $branch]($style) "
symbol = ""

[cmd_duration]
format = "[$duration]($style) "
