version: v0.8.4
modes:
  builtin:
    default:
      key_bindings:
        on_key:
          ctrl-f:
            help: search with preview
            messages:
              - BashExec: |
                  PTH=$(cat "${XPLR_PIPE_DIRECTORY_NODES_OUT:?}" | awk -F / '{print $NF}' | sk --preview "pistol {}")
                  if [ -d "$PTH" ]; then
                      echo ChangeDirectory: $PWD/${PTH:?} >> "${XPLR_PIPE_MSG_IN:?}"
                  elif [ -f "$PTH" ]; then
                      echo FocusPath: $PWD/${PTH:?} >> "${XPLR_PIPE_MSG_IN:?}"
                  fi
              - SwitchMode: default
          y:
            help: copy
            messages:
              - SwitchMode: copy
          p:
            help: paste
            messages:
              - BashExecSilently: |
                  xclip-pastefile > /dev/null && echo ExplorePwdAsync >> "${XPLR_PIPE_MSG_IN:?}"
          R:
            help: batch rename
            messages:
              - BashExec: |
                  SELECTION=$(cat "${XPLR_PIPE_SELECTION_OUT:?}")
                  NODES=${SELECTION:-$(cat "${XPLR_PIPE_DIRECTORY_NODES_OUT:?}")}
                  if [ "$NODES" ]; then
                    mmv $NODES
                    echo ExplorePwdAsync >> "${XPLR_PIPE_MSG_IN:?}"
                  fi
          D:
            help: disk usage
            messages:
              - BashExec: |
                  dua i
              - ClearScreen
  custom:
    copy:
      name: copy
      key_bindings:
        on_key:
          y:
            help: copy focused file
            messages:
              - BashExecSilently: |
                  xclip-copyfile $(cat "${XPLR_PIPE_RESULT_OUT:?}")
              - SwitchMode: default
        default:
          messages:
            - SwitchMode: default
node_types:
  directory:
    meta:
      icon: 
  file:
    meta:
      icon: 
  symlink:
    meta:
      icon: 
